### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Pdzoc** [foundersandcoders/recommended-materials#4]
https://bdcampbell.net/javascript/book/javascript_the_good_parts.pdf - returned 404 Error.

**Comment by nelsonic** [comment]
Hey @Pdzoc 👋 hope you’re well. 🤞🏼
Thanks for opening this issue to report the 404 link. 💔 
we probably shouldn’t be linking to copyright-infringing material, even if we aren’t _hosting_ it … 🙄
But it’s quite easy to find via Google: 

[Javascript-The-Good-Parts-Douglas-Crockford-2008.pdf](https://github.com/mystroken/JSBooks/blob/master/%5BJavaScript%20The%20Good%20Parts%201st%20Edition%20by%20Douglas%20Crockford%20-%202008%5D.pdf)

Copy-pasteable Md:
```md
[Javascript-The-Good-Parts-Douglas-Crockford-2008.pdf](https://github.com/mystroken/JSBooks/blob/master/%5BJavaScript%20The%20Good%20Parts%201st%20Edition%20by%20Douglas%20Crockford%20-%202008%5D.pdf)
```

Consider linking to the notes  @iteles made on the book as a decent substitute/enhancement : https://github.com/dwyl/Javascript-the-Good-Parts-notes 💭
